add_requires("doctest", {plat = get_config("host"), arch = os.arch(), configs = {toolchains = get_config("toolchain_host")}})
set_arch(os.arch())
set_plat(get_config("host"))
add_packages("doctest")

target("unit_test_utils")
    add_files("utils.cppm", {public = true})
    add_files("main.cpp")
    add_deps("SoC.freestanding.unit_test")
    set_kind("shared")
    add_rules("utils.symbols.export_all", {export_classes = true})
    set_enabled(get_config("build_unit_test"))
target_end()
target("unit_test")
    add_files("*.cpp|main.cpp")
    add_deps("unit_test_utils")
    set_kind("binary")
    set_policy("build.c++.modules.fallbackscanner", true)
    set_enabled(get_config("build_unit_test"))

    for _, file in ipairs(os.files("*.cpp|main.cpp")) do
        local name = path.basename(file)
        add_tests(name, {runargs = {"-ts", name}})
    end
target_end()
