target("cmsis")
    set_kind("static")
    add_includedirs("include", {public = true})
    add_rules("release")
    add_undefines("_DEBUG", "DEBUG")
    add_files("src/*.c", "src/*.cpp", "src/*.s")
target_end()
