includes("script/toolchains/xmake/*.lua")
set_project("SoC")
set_version("0.1.0")
set_xmakever("2.9.0")
set_warnings("allextra")
set_languages("clatest", "cxxlatest")
set_allowedmodes(support_rules_table)
set_defaultmode("debug")
set_rules(get_config("mode"))
set_config("march", "armv7-m")
add_defines("STM32F407xx")
includes("*/xmake.lua")
