add_cxxflags("-Wno-experimental-header-units")
includes("*/xmake.lua")
target("SoC.stm32")
    set_kind("static")
    add_deps("stm32f4_hal_ll", "SoC.std", "SoC.freestanding", "SoC.crt")
    add_files("include/*.cppm", {public = true})
    add_files("src/*.cppm")
    add_extrafiles("assets/*")
    set_pcxxheader("include/pch.hpp")
    add_includedirs("include")
target_end()
