add_cxxflags("-Wno-experimental-header-units")
includes("*/xmake.lua")
target("SoC.stm32")
    set_kind("static")
    add_deps("stm32f4_hal_ll", "SoC.std", "SoC.freestanding", "SoC.crt")
    add_files("include/*.cppm", {public = true})
    add_files("src/*.cpp")
    add_extrafiles("assets/*")
    set_policy("build.c++.modules.fallbackscanner", true)
target_end()
