option("assert", function()
    set_default(true)
    set_description("Whether to use assert in stm32 hal/ll and SoC.")
    add_defines("USE_FULL_ASSERT")
end)

option("build_unit_test", function()
    set_default(true)
    set_description("Whether to build unit test.")
end)

option("unit_test_with_asan", function()
    set_default(true)
    set_description("Whether to build unit test with address sanitizer.")
end)

option("unit_test_with_ubsan", function()
    set_default(true)
    set_description("Whether to build unit test with undefined behavior sanitizer.")
end)

option("hse_value", function()
    set_default("8000000u")
    set_description("The frequency of high speed external crystal oscillator in Hz.")

    after_check(function(option)
        option:add("defines", "HSE_VALUE=" .. option:value())
    end)
end)

option("_custom_mode", function()
    includes(path.join(os.scriptdir(), "../toolchains/xmake/rule.lua"))
    set_values(table.unpack(support_rules_table))
    set_default(get_config("mode"))
    set_description("The build mode for third party package.")
end)
