add_cxxflags("-Wno-experimental-header-units")
includes("freestanding/xmake.lua")
target("SoC")
    add_deps("stm32f4_hal_ll")
    add_files("src/*.cpp", "src/*.ld")
    add_extrafiles("assets/*")
    add_includedirs("include")
    set_pcxxheader("include/pch.hpp")
    set_extension(".elf")
target_end()
