target("SoC")
    add_deps("hal_ll")
    add_files("src/*.cpp", "src/*.ld")
    add_includedirs("include")
    set_pcxxheader("include/pch.hpp")
    set_extension(".elf")
    after_build(function (target, opt)
        import("core.project.depend")
        import("utils.progress")
        objcopy, _ = target:tool("objcopy")
        target_file = target:targetfile()
        ihex_file_name = path.filename(target:name()) .. ".hex"
        ihex_file = path.join(target:targetdir(), ihex_file_name)
        commands = { objcopy, target_file, "-O", "ihex", ihex_file }
        depend.on_changed(function ()
            local command = table.concat(commands, " ")
            progress.show(opt.progress, "${color.build.target}objcopy %s -> %s", target:name(), ihex_file_name)
            os.vrun(command)
        end, { changed = target:is_rebuilt(), files = { target_file, ihex_file }, values = commands })
    end)
target_end()
