#pragma once
#include <arm_acle.h>
#include <stm32f4xx_ll_bus.h>
#include <stm32f4xx_ll_cortex.h>
#include <stm32f4xx_ll_gpio.h>
#include <stm32f4xx_ll_system.h>
#include <stm32f4xx_ll_tim.h>
#include <stm32f4xx_ll_usart.h>
#include <stm32f4xx_ll_utils.h>
#include <stm32f4xx_ll_rcc.h>
#include <cstdint>
#include <cstddef>
#include <utility>
#include <charconv>
#include <cmath>
#include <concepts>
#include <ratio>
#include <functional>
#include <source_location>
#include <bit>
#include <span>
#include <ranges>
#include <string_view>
#include <stm32_assert.h>
